commands:
  title: 'Игровые команды'

rules:
  title: 'Правила'

faq:
  title: 'Часто задаваемые вопросы'

admins:
  title: 'Администрация'

about:
  title: 'О проекте'

banned:
  title: 'Неудачники'

server-classic:
  title: 'Classic'

server-mini-games:
  title: 'Mini-Games'