# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            id: app.sha1_encoder

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:

        users:
            entity:
                class: AppBundle:User
                property: login


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: users

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            form_login:
                login_path: login
                check_path: login
                target_path_parameter: go_to
                failure_path_parameter: back_to
                username_parameter: username
                password_parameter: password

            logout: true

    access_control:
        - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/administration, roles: ROLE_ADMIN }
        - { path: ^/payment/order/, ips: [127.0.0.1], host: robocassa\.ru$ }