AppBundle\Entity\User:
    exclusion_policy: ALL
    virtual_properties:
        getSkin:
            serialized_name: skin
            type: string
    properties:
        id:
            expose: true
        login:
            expose: true
        regDate:
            expose: true
        serverID:
            expose: true